In [30]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

INPUT_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "retail_sales_clean.csv"
)

print("Project root:")
print(PROJECT_ROOT)

print("\nDataset path:")
print(INPUT_FILE)

print("\nDoes file exist?")
print(INPUT_FILE.exists())

Project root:
d:\PROJECTS\Retail-Sales-Intelligence

Dataset path:
d:\PROJECTS\Retail-Sales-Intelligence\data\processed\retail_sales_clean.csv

Does file exist?
True

In [10]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

pd.set_option("display.max_columns", None)

df = pd.read_csv(
    "../data/processed/retail_sales_clean.csv"
)

df["Order_Date"] = pd.to_datetime(
    df["Order_Date"]
)

print("Dataset shape:", df.shape)

df.head()

Dataset shape: (10000, 22)

,Order_ID,Order_Date,Product_ID,Product_Name,Category,Region,Customer_Type,Quantity,Unit_Price,Discount,Revenue,Cost,Profit,Payment_Method,Year,Month,Month_Name,Quarter,Day,Day_Name,Profit_Margin,Discount_Amount
0,ORD05525,2024-01-01,P001,Laptop,Electronics,North,Regular,4,63932.07,5,242941.87,191469.35,51472.52,Debit Card,2024,1,January,Q1,1,Monday,21.19,12786.41
1,ORD05170,2024-01-01,P002,Smartphone,Electronics,West,New,1,25696.76,5,24411.92,20235.94,4175.98,UPI,2024,1,January,Q1,1,Monday,17.11,1284.84
2,ORD03561,2024-01-01,P022,Coffee,Grocery,South,Premium,11,751.24,5,7850.46,5185.32,2665.14,Credit Card,2024,1,January,Q1,1,Monday,33.95,413.18
3,ORD05768,2024-01-01,P026,Backpack,Accessories,South,Premium,5,1957.06,10,8806.77,6412.37,2394.40,Cash,2024,1,January,Q1,1,Monday,27.19,978.53
4,ORD05661,2024-01-01,P027,Wallet,Accessories,West,Regular,4,1123.24,0,4492.96,3838.23,654.73,Cash,2024,1,January,Q1,1,Monday,14.57,0.00

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         10000 non-null  str
 1   Order_Date       10000 non-null  datetime64[us]
 2   Product_ID       10000 non-null  str
 3   Product_Name     10000 non-null  str
 4   Category         10000 non-null  str
 5   Region           10000 non-null  str
 6   Customer_Type    10000 non-null  str
 7   Quantity         10000 non-null  int64
 8   Unit_Price       10000 non-null  float64
 9   Discount         10000 non-null  int64
 10  Revenue          10000 non-null  float64
 11  Cost             10000 non-null  float64
 12  Profit           10000 non-null  float64
 13  Payment_Method   10000 non-null  str
 14  Year             10000 non-null  int64
 15  Month            10000 non-null  int64
 16  Month_Name       10000 non-null  str
 17  Quarter          10000 non-null  str
 18  Day              10000 non-null  int64
 19  Day_Name         10000 non-null  str
 20  Profit_Margin    10000 non-null  float64
 21  Discount_Amount  10000 non-null  float64
dtypes: datetime64[us](1), float64(6), int64(5), str(10)
memory usage: 2.3 MB

In [12]:
df.describe()

,Order_Date,Quantity,Unit_Price,Discount,Revenue,Cost,Profit,Year,Month,Day,Profit_Margin,Discount_Amount
count,10000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-05-13 11:42:00,4.012600,11082.969615,6.775500,26817.70695,20463.144730,6354.562227,2024.901200,6.092500,15.537800,23.483397,1930.025065
min,2024-01-01 00:00:00,1.000000,100.120000,0.000000,108.33000,72.060000,14.860000,2024.000000,1.000000,1.000000,12.000000,0.000000
25%,2024-09-06 00:00:00,2.000000,1111.667500,0.000000,3447.09250,2613.270000,755.462500,2024.000000,3.000000,8.000000,17.890000,0.000000
50%,2025-05-11 00:00:00,3.000000,2269.050000,5.000000,8073.56500,6219.870000,1818.665000,2025.000000,6.000000,15.000000,23.430000,346.170000
75%,2026-01-16 00:00:00,5.000000,12307.220000,10.000000,23641.44000,18217.232500,5451.120000,2026.000000,9.000000,23.000000,29.142500,1343.507500
max,2026-09-30 00:00:00,14.000000,89958.910000,20.000000,359549.12000,283784.630000,120073.710000,2026.000000,12.000000,31.000000,35.000000,71908.340000
std,NaN,3.045582,19068.202976,5.965204,49295.14585,37593.026157,12427.008349,0.787338,3.331524,8.805131,6.616581,5039.279526

In [13]:
category_sales = (
    df.groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

category_sales

Category
Electronics    2.037280e+08
Furniture      2.990092e+07
Clothing       1.659948e+07
Grocery        1.075780e+07
Accessories    7.190835e+06
Name: Revenue, dtype: float64

In [14]:
fig = px.bar(
    category_sales,
    x=category_sales.index,
    y=category_sales.values,
    title="Revenue by Product Category",
    labels={
        "x": "Category",
        "y": "Revenue"
    }
)

fig.show()

In [15]:
region_sales = (
    df.groupby("Region")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

region_sales

Region
South    96101026.19
North    66317261.16
West     66007354.52
East     39751427.63
Name: Revenue, dtype: float64

In [16]:
fig = px.bar(
    region_sales,
    x=region_sales.index,
    y=region_sales.values,
    title="Revenue by Region",
    labels={
        "x": "Region",
        "y": "Revenue"
    }
)

fig.show()

In [17]:
monthly_sales = (
    df.groupby(df["Order_Date"].dt.to_period("M"))["Revenue"]
    .sum()
    .reset_index()
)

monthly_sales.head()

  Order_Date     Revenue
0    2024-01  9008913.60
1    2024-02  9211719.11
2    2024-03  8790026.00
3    2024-04  7132025.25
4    2024-05  8077706.06

In [18]:
monthly_sales["Order_Date"] = monthly_sales["Order_Date"].dt.to_timestamp()

fig = px.line(
    monthly_sales,
    x="Order_Date",
    y="Revenue",
    markers=True,
    title="Monthly Revenue Trend",
    labels={
        "Order_Date": "Month",
        "Revenue": "Revenue"
    }
)

fig.show()

In [19]:
# Monthly Revenue Trend

monthly_sales = (
    df.groupby(
        df["Order_Date"].dt.to_period("M")
    )["Revenue"]
    .sum()
    .reset_index()
)

monthly_sales["Order_Date"] = (
    monthly_sales["Order_Date"]
    .dt.to_timestamp()
)

monthly_sales.head()

  Order_Date     Revenue
0 2024-01-01  9008913.60
1 2024-02-01  9211719.11
2 2024-03-01  8790026.00
3 2024-04-01  7132025.25
4 2024-05-01  8077706.06

In [20]:
top_products = (
    df.groupby("Product_Name")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Product_Name
Laptop          1.141339e+08
Smartphone      3.585070e+07
Tablet          2.616152e+07
Monitor         1.505601e+07
Bed             8.976078e+06
Sofa            8.213017e+06
Smart Watch     5.812033e+06
Study Table     5.246328e+06
Office Chair    5.036570e+06
Shoes           4.720928e+06
Name: Revenue, dtype: float64

In [21]:
fig = px.bar(
    top_products.sort_values(),
    orientation="h",
    title="Top 10 Products by Revenue",
    labels={
        "value": "Revenue",
        "Product_Name": "Product"
    }
)

fig.show()

In [22]:
customer_sales = (
    df.groupby("Customer_Type")
    .agg(
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
)

customer_sales

  Customer_Type       Revenue       Profit  Orders
0           New  5.380154e+07  13024014.32    2000
1       Premium  5.100636e+07  12119877.86    1967
2       Regular  1.633692e+08  38401730.09    6033

In [23]:
fig = px.pie(
    customer_sales,
    names="Customer_Type",
    values="Revenue",
    title="Revenue Contribution by Customer Type"
)

fig.show()

In [24]:
payment_sales = (
    df.groupby("Payment_Method")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

payment_sales

Payment_Method
Debit Card     55971288.31
Net Banking    55071272.62
Cash           52749633.79
UPI            52310249.97
Credit Card    52074624.81
Name: Revenue, dtype: float64

In [25]:
fig = px.bar(
    payment_sales,
    x=payment_sales.index,
    y=payment_sales.values,
    title="Revenue by Payment Method",
    labels={
        "x": "Payment Method",
        "y": "Revenue"
    }
)

fig.show()

In [26]:
discount_analysis = (
    df.groupby("Discount")
    .agg(
        Revenue=("Revenue", "sum"),
        Profit=("Profit", "sum"),
        Profit_Margin=("Profit_Margin", "mean")
    )
    .reset_index()
)

discount_analysis

   Discount      Revenue       Profit  Profit_Margin
0         0  86896711.00  21086017.87      23.683665
1         5  83482196.24  19436303.76      23.504990
2        10  49384768.99  11486503.15      23.155301
3        15  36503683.18   8659204.94      23.512323
4        20  11909710.09   2877592.55      23.394676

In [27]:
fig = px.line(
    discount_analysis,
    x="Discount",
    y="Profit_Margin",
    markers=True,
    title="Discount vs Average Profit Margin",
    labels={
        "Discount": "Discount (%)",
        "Profit_Margin": "Profit Margin (%)"
    }
)

fig.show()

In [28]:
yearly_sales = (
    df.groupby("Year")["Revenue"]
    .sum()
    .reset_index()
)

yearly_sales["Growth_Percentage"] = (
    yearly_sales["Revenue"]
    .pct_change()
    * 100
)

yearly_sales

   Year      Revenue  Growth_Percentage
0  2024  99507025.90                NaN
1  2025  97624333.15          -1.892020
2  2026  71045710.45         -27.225408

In [29]:
fig = px.bar(
    yearly_sales,
    x="Year",
    y="Revenue",
    title="Yearly Revenue",
    text_auto=".2s",
    labels={
        "Year": "Year",
        "Revenue": "Revenue"
    }
)

fig.show()

In [33]:
import importlib
import src.forecasting as forecasting

importlib.reload(forecasting)

print("INPUT FILE:")
print(forecasting.INPUT_FILE)

print("\nTYPE:")
print(type(forecasting.INPUT_FILE))

print("\nFILE EXISTS:")
print(forecasting.INPUT_FILE.exists())

INPUT FILE:
D:\PROJECTS\Retail-Sales-Intelligence\data\processed\retail_sales_clean.csv

TYPE:
<class 'pathlib.WindowsPath'>

FILE EXISTS:
True

In [34]:
df_forecast = forecasting.load_data()

print("Dataset loaded successfully!")
print("Shape:", df_forecast.shape)

Dataset loaded successfully!
Shape: (10000, 22)

In [35]:
monthly_forecast = forecasting.prepare_monthly_data(
    df_forecast
)

forecast_data = forecasting.create_features(
    monthly_forecast
)

(
    model,
    X_train,
    X_test,
    y_train,
    y_test,
    predictions
) = forecasting.train_model(
    forecast_data
)

metrics = forecasting.evaluate_model(
    y_test,
    predictions
)

print("MODEL PERFORMANCE")
print("-" * 50)

for metric, value in metrics.items():
    print(f"{metric}: {value}")

MODEL PERFORMANCE
--------------------------------------------------
MAE: 996490.16
RMSE: 1116354.77
R2: -0.3767
MAPE: 12.05

In [36]:
future_forecast = forecasting.forecast_future(
    model,
    monthly_forecast,
    periods=6
)

future_forecast

,Month,Time_Index,Month_Number,Month_Sin,Month_Cos,Predicted_Revenue
0,2026-10-01,33,10,-8.660254e-01,5.000000e-01,7603113.09
1,2026-11-01,34,11,-5.000000e-01,8.660254e-01,7713390.54
2,2026-12-01,35,12,-2.449294e-16,1.000000e+00,7721843.22
3,2027-01-01,36,1,5.000000e-01,8.660254e-01,7616321.70
4,2027-02-01,37,2,8.660254e-01,5.000000e-01,7415215.82
5,2027-03-01,38,3,1.000000e+00,6.123234e-17,7162527.18

In [37]:
from src import forecasting

import importlib

importlib.reload(forecasting)

df_forecast = forecasting.load_data()

monthly_forecast = (
    forecasting.prepare_monthly_data(
        df_forecast
    )
)

model = forecasting.create_model()

model.fit(
    forecasting.create_features(
        monthly_forecast
    )
    .dropna()[
        forecasting.FEATURE_COLUMNS
    ],
    forecasting.create_features(
        monthly_forecast
    )
    .dropna()["Revenue"]
)

future_forecast = (
    forecasting.forecast_future(
        model,
        monthly_forecast,
        periods=6
    )
)

future_forecast

       Month  Predicted_Revenue
0 2026-10-01         8057168.04
1 2026-11-01         7623432.51
2 2026-12-01         7762696.36
3 2027-01-01         7810745.73
4 2027-02-01         7747989.79
5 2027-03-01         7703660.50

In [38]:
import plotly.graph_objects as go


fig = go.Figure()


# Historical Revenue
fig.add_trace(
    go.Scatter(
        x=monthly_forecast["Month"],
        y=monthly_forecast["Revenue"],
        mode="lines+markers",
        name="Historical Revenue"
    )
)


# Forecast Revenue
fig.add_trace(
    go.Scatter(
        x=future_forecast["Month"],
        y=future_forecast["Predicted_Revenue"],
        mode="lines+markers",
        name="Forecast Revenue",
        line=dict(
            dash="dash"
        )
    )
)


fig.update_layout(
    title="Revenue Forecast - Next 6 Months",
    xaxis_title="Month",
    yaxis_title="Revenue (₹)",
    hovermode="x unified",
    template="plotly_white"
)


fig.show()